#include "../../Structs.h"

static struct Rotation3AnimData r3ad_104D6E40[] =
{
    { 0, { 0, 0, 0 } },
    { 1, { 0, 0, 9362 } },
    { 2, { 0, 0, 18724 } },
    { 3, { 0, 0, 28086 } },
    { 4, { 0, 0, 37448 } },
    { 5, { 0, 0, 46810 } },
    { 6, { 0, 0, 56172 } }
};

static struct AnimFrame_PosRot afpr_104D6EB0[] =
{
    { NULL, r3ad_104D6E40, 0, ARRAYSIZE(r3ad_104D6E40) },
    { NULL, NULL, 0, 0 },
    { NULL, NULL, 0, 0 },
    { NULL, NULL, 0, 0 },
    { NULL, NULL, 0, 0 },
    { NULL, NULL, 0, 0 },
    { NULL, NULL, 0, 0 },
    { NULL, NULL, 0, 0 },
    { NULL, NULL, 0, 0 },
    { NULL, NULL, 0, 0 },
    { NULL, NULL, 0, 0 },
    { NULL, NULL, 0, 0 },
    { NULL, NULL, 0, 0 },
    { NULL, NULL, 0, 0 },
    { NULL, NULL, 0, 0 },
    { NULL, NULL, 0, 0 },
    { NULL, NULL, 0, 0 },
    { NULL, NULL, 0, 0 },
    { NULL, NULL, 0, 0 },
    { NULL, NULL, 0, 0 },
    { NULL, NULL, 0, 0 },
    { NULL, NULL, 0, 0 },
    { NULL, NULL, 0, 0 },
    { NULL, NULL, 0, 0 },
    { NULL, NULL, 0, 0 },
    { NULL, NULL, 0, 0 },
    { NULL, NULL, 0, 0 },
    { NULL, NULL, 0, 0 },
    { NULL, NULL, 0, 0 },
    { NULL, NULL, 0, 0 },
    { NULL, NULL, 0, 0 },
    { NULL, NULL, 0, 0 },
    { NULL, NULL, 0, 0 },
    { NULL, NULL, 0, 0 },
    { NULL, NULL, 0, 0 },
    { NULL, NULL, 0, 0 },
    { NULL, NULL, 0, 0 },
    { NULL, NULL, 0, 0 },
    { NULL, NULL, 0, 0 },
    { NULL, NULL, 0, 0 },
    { NULL, NULL, 0, 0 },
    { NULL, NULL, 0, 0 },
    { NULL, NULL, 0, 0 },
    { NULL, NULL, 0, 0 },
    { NULL, NULL, 0, 0 },
    { NULL, NULL, 0, 0 },
    { NULL, NULL, 0, 0 },
    { NULL, NULL, 0, 0 },
    { NULL, NULL, 0, 0 },
    { NULL, NULL, 0, 0 },
    { NULL, NULL, 0, 0 },
    { NULL, NULL, 0, 0 },
    { NULL, NULL, 0, 0 },
    { NULL, NULL, 0, 0 },
    { NULL, NULL, 0, 0 },
    { NULL, NULL, 0, 0 },
    { NULL, NULL, 0, 0 },
    { NULL, NULL, 0, 0 },
    { NULL, NULL, 0, 0 },
    { NULL, NULL, 0, 0 },
    { NULL, NULL, 0, 0 },
    { NULL, NULL, 0, 0 },
    { NULL, NULL, 0, 0 },
    { NULL, NULL, 0, 0 },
    { NULL, NULL, 0, 0 },
    { NULL, NULL, 0, 0 },
    { NULL, NULL, 0, 0 },
    { NULL, NULL, 0, 0 },
    { NULL, NULL, 0, 0 }
};

struct AnimHead2 ah2_104D7300 =
{
    afpr_104D6EB0,
    7,
    AnimHead2Flags_HasPosition | AnimHead2Flags_HasRotation,
    0x0002
};
